version: '3.7'

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=rentx_user
      - POSTGRES_PASSWORD=rentx_password
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  pgdata:
    driver: local