name: CI

on: 
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          
      - name: Install dependecies
      - run: npm install
      
      - name: Build app
      - run: npm run vuild
      
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "., !node_modules"
          target: "test"
